### ISSUE TITLE
Switch to a different charting package

### ISSUE THREAD

**Issue by tkeffer** [tkeffer/weert-js#19]
Recharts seems to be dead.

Two lead candidates: 
[react-timeseries-charts](https://github.com/esnet/react-timeseries-charts)
[react-vis (from Uber)](https://uber.github.io/react-vis/)

**Comment by gjr80** [comment]
Looking at this again just now it seems the tables have turned; `Recharts` has a new lease of life and `react-timeseries-charts` and `react-vis (from Uber)` have died to some extent with no release since August 2018 and April 2019 respectively. I say stick with `Recharts` for now.

**Comment by tkeffer** [comment]
Right. I'll tell the development team. :-)

**Comment by gjr80** [comment]
:rofl:
