### ISSUE TITLE
WeeWX 3.9.1-1 not supported?

### ISSUE THREAD

**Issue by MichaelAronsen** [tkeffer/weert-js#21]
I got everything installed and built fine, but when WeeWX tries to send a packet, I get these log messages from WeeWX:
Jul 26 10:41:06 weewx weewx[14766]: restx: WeeRT: Unexpected exception of type <type 'exceptions.AttributeError'>
Jul 26 10:41:06 weewx weewx[14766]: *** Traceback (most recent call last):
Jul 26 10:41:06 weewx weewx[14766]: ***   File "/usr/share/weewx/weewx/restx.py", line 350, in run_loop
Jul 26 10:41:06 weewx weewx[14766]: ***     self.process_record(_record, dbmanager)
Jul 26 10:41:06 weewx weewx[14766]: ***   File "/usr/share/weewx/weewx/restx.py", line 393, in process_record
Jul 26 10:41:06 weewx weewx[14766]: ***     _full_record = self.get_record(record, dbmanager)
Jul 26 10:41:06 weewx weewx[14766]: ***   File "/usr/share/weewx/weewx/restx.py", line 263, in get_record
Jul 26 10:41:06 weewx weewx[14766]: ***     _result = dbmanager.getSql(
Jul 26 10:41:06 weewx weewx[14766]: *** AttributeError: 'NoneType' object has no attribute 'getSql'
Jul 26 10:41:06 weewx weewx[14766]: restx: WeeRT: Thread exiting. Reason: 'NoneType' object has no attribute 'getSql'
Jul 26 10:41:16 weewx weewx[14766]: interceptor: MainThread: empty queue
Jul 26 10:41:36 weewx weewx[14766]: message repeated 2 times: [ interceptor: MainThread: empty queue]

**Comment by tkeffer** [comment]
I believe this was fixed in WeeWX 3.9.2. Try that. If not, we'll reopen the issue.

**Comment by maikosoft** [comment]
> I believe this was fixed in WeeWX 3.9.2. Try that. If not, we'll reopen the issue.

Thanks

**Comment by MichaelAronsen** [comment]
It was indeed fixed, thanks.

Funnily, weewx.com went down while I ran apt upgrade..
