### ISSUE TITLE
Commits beyond Sept 29 2022 Client not building

### ISSUE THREAD

**Issue by bhaal2** [tkeffer/weert-js#66]
Hi Tom,

Just wanted to make a note that commits made from Sept 29 2022 onwards and inclusive are failing to compile either due to module dependencies or code issues. "ff5555a25b1495b0db4f53f576c11f219f15931b" is sha for the last commit that works.  If you can't reproduce this, I will redo all the stuff I did before getting to this point and add it here, let me know.  Thanks.

**Comment by tkeffer** [comment]
There have been a bunch of automatic security updates done by GitHub via PRs. I've just been blindly accepting them. Unfortunately, a couple of them have merge conflicts.

I'll get around to taking a look, but it could take some time. Some things, Webpack in particular, have had some big revisions, which takes time to sort through.
